### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by vlferrini** [zimonkaizoku/homebrew-mbsystem#1]
I'm unable to complete the installation due to this error:

==> make check
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libmbio.la] Error 1
make[2]: *** [check] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

Any suggestions?

**Comment by zimonkaizoku** [comment]
This git only holds the formula for the homebrew installation of mbsystem. What you have here seems to be a compiling error which should be related to the mbsystem code. Therefore I would like to refer you to the mbsystem mailing list:
`http://listserver.mbari.org/sympa/subscribe/mbsystem`

**Comment by dwcaress** [comment]
Vicki,
That�s not much information, but it might be failing to write the linked objects into /usr/local/bin or /usr/local/lib.
Make sure that you have write permission in /usr/local/ 
Homebrew doesn�t let you run it as sudo, but still fails if you don�t have write permission where it is trying to install. I had to set permissions before I could get it to work at all.
Cheers,
Dave


On Jun 2, 2015, at 4:05 AM, Vicki Ferrini <notifications@github.com> wrote:

> I'm unable to complete the installation due to this error:
> 
> ==> make check
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[3]: *** [libmbio.la] Error 1
> make[2]: *** [check] Error 2
> make[1]: *** [check-recursive] Error 1
> make: *** [check-recursive] Error 1
> 
> Any suggestions?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

----------------------------------------------------
David W. Caress
Software Engineer

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

caress@mbari.org
http://www.mbari.org/~caress/

Phone: 831-775-1775
Fax: 831-775-1620

**Comment by vlferrini** [comment]
Thanks Dave - we were finally able to fix things. 
Your suggestion of changing the permissions helped. The homebrew formula (rb file) also had to be modified locally because it was making the assumption that the netcdf libraries and includes were in the GMT libraries and includes directories.  By pointing to the netcdf libraries and includes directly we were able to compile.

**Comment by zimonkaizoku** [comment]
Great!
And you are right, there's a copy paste bug in the formula. Already fixed!
Funny enough that it caused a problem for you but not for me...

**Comment by zimonkaizoku** [comment]
Great!
And you are right, there's a copy paste bug in the formula. Already fixed!
Funny enough that it caused a problem for you but not for me...
