### ISSUE TITLE
openmotif failed to build 10.10.5

### ISSUE THREAD

**Issue by jtarp26** [zimonkaizoku/homebrew-mbsystem#3]
Bug reports:

I'm attempting to install the mbsystem package, using the patch from Homebrew/homebrew-x11#255 as instructed by the MBsystem support team. I fixed all issues from 'brew doctor' and below is the output from 'brew config'. The URL to the gist-log is "https://gist.github.com/anonymous/cab6bc323cec23b89abc1e1bef400e26". I am new to github and using command line, so apologies for any ignorance on my part. With that said, I'd really appreciate being pointed in the right direction as I cannot make heads or tails of this.

HOMEBREW_VERSION: 1.1.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 99f42146c06333f820f45ed1940c5487990e2b31
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16c4d6b
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11

**Comment by zimonkaizoku** [comment]
With [#270](https://github.com/Homebrew/homebrew-x11/pull/270) this should be fixed and manual patching should not be necessary. But I have not tried that yet.
That said, I don't quite understand what your issue is. Did openmotif not install? Did mbsystem not install?

Please run the following commands:

```
brew update
brew upgrade
brew install zimonkaizoku/mbsystem/otps --with-tpxo8
brew install zimonkaizoku/mbsystem/mbsystem
```

Carefully read the caveats and other output throughout the installation and follow the instructions. If there are any errors during installation, please copy the output in here.

**Comment by jtarp26** [comment]
I received the below output after using the last command.

==> make check
Last 15 lines from /Users/jtran/Library/Logs/Homebrew/mbsystem/02.make:
mv -f .deps/mbr_mgd77txt.Tpo .deps/mbr_mgd77txt.Plo
/bin/sh ../../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -I../../src/mbaux -I../../src/bsio -I../../src/surf -I../../src/gsf -I/usr/local/Cellar/gmt/5.1.2/include/gmt -I/usr/local/Cellar/netcdf/4.4.1.1/include  -I/usr/local/opt/proj/include    -I/opt/X11/include -L/opt/X11/lib -MT mbr_photgram.lo -MD -MP -MF .deps/mbr_photgram.Tpo -c -o mbr_photgram.lo mbr_photgram.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src/mbaux -I../../src/bsio -I../../src/surf -I../../src/gsf -I/usr/local/Cellar/gmt/5.1.2/include/gmt -I/usr/local/Cellar/netcdf/4.4.1.1/include -I/usr/local/opt/proj/include -I/opt/X11/include -L/opt/X11/lib -MT mbr_photgram.lo -MD -MP -MF .deps/mbr_photgram.Tpo -c mbr_photgram.c  -fno-common -DPIC -o .libs/mbr_photgram.o
mv -f .deps/mbr_wasspenl.Tpo .deps/mbr_wasspenl.Plo
mv -f .deps/mbr_mgd77tab.Tpo .deps/mbr_mgd77tab.Plo
mv -f .deps/mbr_photgram.Tpo .deps/mbr_photgram.Plo
mv -f .deps/mbr_mbnetcdf.Tpo .deps/mbr_mbnetcdf.Plo
/bin/sh ../../libtool  --tag=CC   --mode=link clang   -I/opt/X11/include -L/opt/X11/lib -no-undefined -version-info 0:0:0 -m64 -o libmbio.la -rpath /usr/local/Cellar/mbsystem/5.5.2284/lib mb_format.lo mb_error.lo mb_swap.lo mb_compare.lo mb_navint.lo mb_read_init.lo mb_write_init.lo mb_close.lo mb_fileio.lo mb_mem.lo mb_coor_scale.lo mb_check_info.lo mb_time.lo mb_angle.lo mb_absorption.lo mb_proj.lo mb_spline.lo mb_get_value.lo mb_defaults.lo mb_process.lo mb_esf.lo mb_get.lo mb_get_all.lo mb_read.lo mb_put_all.lo mb_put_comment.lo mb_buffer.lo mb_platform.lo mb_platform_math.lo mb_read_ping.lo mb_write_ping.lo mb_access.lo mb_segy.lo mb_rt.lo mbsys_sb.lo mbsys_hsds.lo mbsys_sb2100.lo mbsys_simrad.lo mbsys_simrad2.lo mbsys_simrad3.lo mbsys_mr1.lo mbsys_mr1b.lo mbsys_mr1v2001.lo mbsys_ldeoih.lo mbsys_reson.lo mbsys_elac.lo mbsys_elacmk2.lo mbsys_sb2000.lo mbsys_hsmd.lo mbsys_dsl.lo mbsys_mstiff.lo mbsys_oic.lo mbsys_hdcs.lo mbsys_singlebeam.lo mbsys_xse.lo mbsys_hs10.lo mbsys_atlas.lo mbsys_surf.lo mbsys_reson8k.lo mbsys_gsf.lo mbr_gsfgenmb.lo mbsys_netcdf.lo mbsys_navnetcdf.lo mbsys_reson7k.lo mbsys_jstar.lo mbsys_image83p.lo mbsys_hysweep.lo mbsys_benthos.lo mbsys_swathplus.lo mbsys_3datdepthlidar.lo mbsys_wassp.lo mbsys_stereopair.lo mbr_sbsiomrg.lo mbr_sbsiocen.lo mbr_sbsiolsi.lo mbr_sburicen.lo mbr_sburivax.lo mbr_sbifremr.lo mbr_hsatlraw.lo mbr_hsldedmb.lo mbr_hsuricen.lo mbr_hsurivax.lo mbr_hsldeoih.lo mbr_hsunknwn.lo mbr_sb2100rw.lo mbr_sb2100bi.lo mbr_emoldraw.lo mbr_em12darw.lo mbr_em12ifrm.lo mbr_em300raw.lo mbr_em300mba.lo mbr_em710raw.lo mbr_em710mba.lo mbr_mr1prhig.lo mbr_mr1aldeo.lo mbr_mr1bldeo.lo mbr_mr1prvr2.lo mbr_mbldeoih.lo mbr_cbat9001.lo mbr_cbat8101.lo mbr_hypc8101.lo mbr_bchrtunb.lo mbr_elmk2unb.lo mbr_bchrxunb.lo mbr_l3xseraw.lo mbr_sbsioswb.lo mbr_sb2000sb.lo mbr_sb2000ss.lo mbr_hsmdaraw.lo mbr_hsmdldih.lo mbr_dsl120pf.lo mbr_dsl120sf.lo mbr_mstiffss.lo mbr_oicgeoda.lo mbr_oicmbari.lo mbr_omghdcsj.lo mbr_mgd77dat.lo mbr_asciixyz.lo mbr_hydrob93.lo mbr_mbarirov.lo mbr_mbarrov2.lo mbr_mbpronav.lo mbr_hs10jams.lo mbr_hsds2raw.lo mbr_hsds2lam.lo mbr_xtfr8101.lo mbr_mbnetcdf.lo mbr_nvnetcdf.lo mbr_samesurf.lo mbr_reson7kr.lo mbr_edgjstar.lo mbr_segysegy.lo mbr_image83p.lo mbr_imagemba.lo mbr_hir2rnav.lo mbr_hysweep1.lo mbr_xtfb1624.lo mbr_swplssxi.lo mbr_swplssxp.lo mbr_3ddepthp.lo mbr_wasspenl.lo mbr_mgd77txt.lo mbr_mgd77tab.lo mbr_photgram.lo  ../../src/bsio/libmbbsio.la ../../src/surf/libmbsapi.la ../../src/gsf/libmbgsf.la -L/usr/local/Cellar/gmt/5.1.2/lib -R /usr/local/Cellar/gmt/5.1.2/lib -lgmt -lpostscriptlight -L/usr/local/Cellar/netcdf/4.4.1.1/lib -lnetcdf -L/usr/local/opt/proj/lib -R /usr/local/opt/proj/lib -lproj  -lm 
libtool: link: clang -dynamiclib  -o .libs/libmbio.0.dylib  .libs/mb_format.o .libs/mb_error.o .libs/mb_swap.o .libs/mb_compare.o .libs/mb_navint.o .libs/mb_read_init.o .libs/mb_write_init.o .libs/mb_close.o .libs/mb_fileio.o .libs/mb_mem.o .libs/mb_coor_scale.o .libs/mb_check_info.o .libs/mb_time.o .libs/mb_angle.o .libs/mb_absorption.o .libs/mb_proj.o .libs/mb_spline.o .libs/mb_get_value.o .libs/mb_defaults.o .libs/mb_process.o .libs/mb_esf.o .libs/mb_get.o .libs/mb_get_all.o .libs/mb_read.o .libs/mb_put_all.o .libs/mb_put_comment.o .libs/mb_buffer.o .libs/mb_platform.o .libs/mb_platform_math.o .libs/mb_read_ping.o .libs/mb_write_ping.o .libs/mb_access.o .libs/mb_segy.o .libs/mb_rt.o .libs/mbsys_sb.o .libs/mbsys_hsds.o .libs/mbsys_sb2100.o .libs/mbsys_simrad.o .libs/mbsys_simrad2.o .libs/mbsys_simrad3.o .libs/mbsys_mr1.o .libs/mbsys_mr1b.o .libs/mbsys_mr1v2001.o .libs/mbsys_ldeoih.o .libs/mbsys_reson.o .libs/mbsys_elac.o .libs/mbsys_elacmk2.o .libs/mbsys_sb2000.o .libs/mbsys_hsmd.o .libs/mbsys_dsl.o .libs/mbsys_mstiff.o .libs/mbsys_oic.o .libs/mbsys_hdcs.o .libs/mbsys_singlebeam.o .libs/mbsys_xse.o .libs/mbsys_hs10.o .libs/mbsys_atlas.o .libs/mbsys_surf.o .libs/mbsys_reson8k.o .libs/mbsys_gsf.o .libs/mbr_gsfgenmb.o .libs/mbsys_netcdf.o .libs/mbsys_navnetcdf.o .libs/mbsys_reson7k.o .libs/mbsys_jstar.o .libs/mbsys_image83p.o .libs/mbsys_hysweep.o .libs/mbsys_benthos.o .libs/mbsys_swathplus.o .libs/mbsys_3datdepthlidar.o .libs/mbsys_wassp.o .libs/mbsys_stereopair.o .libs/mbr_sbsiomrg.o .libs/mbr_sbsiocen.o .libs/mbr_sbsiolsi.o .libs/mbr_sburicen.o .libs/mbr_sburivax.o .libs/mbr_sbifremr.o .libs/mbr_hsatlraw.o .libs/mbr_hsldedmb.o .libs/mbr_hsuricen.o .libs/mbr_hsurivax.o .libs/mbr_hsldeoih.o .libs/mbr_hsunknwn.o .libs/mbr_sb2100rw.o .libs/mbr_sb2100bi.o .libs/mbr_emoldraw.o .libs/mbr_em12darw.o .libs/mbr_em12ifrm.o .libs/mbr_em300raw.o .libs/mbr_em300mba.o .libs/mbr_em710raw.o .libs/mbr_em710mba.o .libs/mbr_mr1prhig.o .libs/mbr_mr1aldeo.o .libs/mbr_mr1bldeo.o .libs/mbr_mr1prvr2.o .libs/mbr_mbldeoih.o .libs/mbr_cbat9001.o .libs/mbr_cbat8101.o .libs/mbr_hypc8101.o .libs/mbr_bchrtunb.o .libs/mbr_elmk2unb.o .libs/mbr_bchrxunb.o .libs/mbr_l3xseraw.o .libs/mbr_sbsioswb.o .libs/mbr_sb2000sb.o .libs/mbr_sb2000ss.o .libs/mbr_hsmdaraw.o .libs/mbr_hsmdldih.o .libs/mbr_dsl120pf.o .libs/mbr_dsl120sf.o .libs/mbr_mstiffss.o .libs/mbr_oicgeoda.o .libs/mbr_oicmbari.o .libs/mbr_omghdcsj.o .libs/mbr_mgd77dat.o .libs/mbr_asciixyz.o .libs/mbr_hydrob93.o .libs/mbr_mbarirov.o .libs/mbr_mbarrov2.o .libs/mbr_mbpronav.o .libs/mbr_hs10jams.o .libs/mbr_hsds2raw.o .libs/mbr_hsds2lam.o .libs/mbr_xtfr8101.o .libs/mbr_mbnetcdf.o .libs/mbr_nvnetcdf.o .libs/mbr_samesurf.o .libs/mbr_reson7kr.o .libs/mbr_edgjstar.o .libs/mbr_segysegy.o .libs/mbr_image83p.o .libs/mbr_imagemba.o .libs/mbr_hir2rnav.o .libs/mbr_hysweep1.o .libs/mbr_xtfb1624.o .libs/mbr_swplssxi.o .libs/mbr_swplssxp.o .libs/mbr_3ddepthp.o .libs/mbr_wasspenl.o .libs/mbr_mgd77txt.o .libs/mbr_mgd77tab.o .libs/mbr_photgram.o   -L/opt/X11/lib ../../src/bsio/.libs/libmbbsio.dylib ../../src/surf/.libs/libmbsapi.dylib ../../src/gsf/.libs/libmbgsf.dylib -L/usr/local/Cellar/gmt/5.1.2/lib -lgmt -lpostscriptlight -L/usr/local/Cellar/netcdf/4.4.1.1/lib -lnetcdf -L/usr/local/opt/proj/lib /usr/local/Cellar/proj/4.9.3/lib/libproj.dylib -lpthread -lm  -m64   -install_name  /usr/local/Cellar/mbsystem/5.5.2284/lib/libmbio.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
ld: library not found for -lpostscriptlight
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libmbio.la] Error 1
make[2]: *** [check] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

**Comment by zimonkaizoku** [comment]
You are trying to install mbsystem 5.5.2284 with gmt 5.1.2. But you need gmt 5.2.1 or later as mentioned in the mbsystem release notes.

If you have done brew update && brew upgrade as stated above, you should have a newer gmt version in place. Check if you have pinned gmt to version 5.1.2, if so, unpin it. Then retry upgrading.

**Comment by jtarp26** [comment]
I have done brew update && brew upgrade. How do I check if gmt is pinned to that version?

**Comment by zimonkaizoku** [comment]
brew list --pinned
brew unpin gmt

**Comment by jtarp26** [comment]
It tells me that gmt is not pinned.

**Comment by zimonkaizoku** [comment]
try
brew upgrade gmt

if that doesn't help, please post the output of
brew info gmt

**Comment by jtarp26** [comment]
>> brew info gmt
homebrew/science/gmt: stable 5.3.1 (bottled)
Tools for processing and displaying xy and xyz datasets
http://gmt.soest.hawaii.edu/
Conflicts with: gmt4
/usr/local/Cellar/gmt/5.1.2 (1,465 files, 225.5M) *
  Poured from bottle on 2015-05-08 at 06:23:41
/usr/local/Cellar/gmt/5.2.1 (1,547 files, 193.5M)
  Poured from bottle on 2016-01-04 at 17:42:30
/usr/local/Cellar/gmt/5.3.1 (1,623 files, 202.3M)
  Poured from bottle on 2016-11-26 at 16:35:48
From: https://github.com/Homebrew/homebrew-science/blob/master/gmt.rb
==> Dependencies
Build: cmake ✘
Required: gdal ✔, netcdf ✔, fftw ✔, pcre ✔
==> Caveats
GMT 5 is mostly (but not 100%) compatible with previous versions.
Moreover, the compatibility mode is expected to exist only during a
transitional period.

If you want to continue using GMT 4:
`brew install gmt4`

We agreed to the `triangle` license
(http://www.cs.cmu.edu/~quake/triangle.html) for you.
If this is unacceptable you should uninstall.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

**Comment by zimonkaizoku** [comment]
ok. That's strange. I think brew switch is deprecated, otherwise you could try
brew switch gmt 5.2.1

other then that I can only think of freshly reinstalling gmt.

brew reinstall gmt
or
brew uninstall gmt && brew install gmt

Anyway somehow your gmt seems to be linked to an older version. It is most likely not an issue with either mbsystem or openmotif.

brew cleanup gmt

might also help. But that will, possibly same as reinstalling, remove your older gmt version.
